name = "ez-db-worker"
main = "worker-db.js"
compatibility_date = "2025-01-01"

# Create a D1 database and bind it here.
# Example:
# wrangler d1 create ezsports-prod
# Then set the binding below (database_id will be printed by Wrangler).

[[d1_databases]]
binding = "DB"
database_name = "ezsports-prod"
database_id = "53d1f79c-2e74-4d18-ae8d-00fab25986c6"

[vars]
# Optional (recommended): shared secret for API access
CF_DB_API_KEY = ""

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
